"""fix_missing_relationships_and_columns

Revision ID: 001ad4541681
Revises: 786511d24a87
Create Date: 2025-11-27 01:39:39.583325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001ad4541681'
down_revision: Union[str, None] = '786511d24a87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Aplicar los cambios a la base de datos (migración hacia adelante).
    """
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Business Config
    op.add_column('business_config', sa.Column('updated_by', sa.Integer(), nullable=True))
    # Use ID 2 (Global Admin) which we know exists
    op.execute("UPDATE business_config SET updated_by = 2 WHERE updated_by IS NULL")
    op.alter_column('business_config', 'updated_by', nullable=False)
    op.create_foreign_key(op.f('fk_business_config_updated_by_global_admins'), 'business_config', 'global_admins', ['updated_by'], ['id'], ondelete='RESTRICT')

    # 2. Financial Reports
    op.add_column('financial_reports', sa.Column('generated_by', sa.Integer(), nullable=True))
    op.execute("UPDATE financial_reports SET generated_by = 2 WHERE generated_by IS NULL")
    op.alter_column('financial_reports', 'generated_by', nullable=False)
    
    op.add_column('financial_reports', sa.Column('shift_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_financial_reports_shift_id_shifts'), 'financial_reports', 'shifts', ['shift_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_financial_reports_generated_by_global_admins'), 'financial_reports', 'global_admins', ['generated_by'], ['id'], ondelete='RESTRICT')

    # 3. Global & Operational Admins (Defaults)
    op.alter_column('global_admins', 'full_name',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               existing_nullable=False)
    op.alter_column('operational_admins', 'full_name',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               existing_nullable=False)

    # 4. Parking Records
    op.add_column('parking_records', sa.Column('shift_id', sa.Integer(), nullable=True))
    op.add_column('parking_records', sa.Column('admin_id', sa.Integer(), nullable=True))
    
    # Try to update with default values if rows exist (Assumes ID 1 exists for Shift/Admin if there is data)
    op.execute("UPDATE parking_records SET shift_id = 1 WHERE shift_id IS NULL")
    op.execute("UPDATE parking_records SET admin_id = 1 WHERE admin_id IS NULL")
    
    op.alter_column('parking_records', 'shift_id', nullable=False)
    op.alter_column('parking_records', 'admin_id', nullable=False)
    
    op.add_column('parking_records', sa.Column('helmet_count', sa.Integer(), nullable=True))
    op.add_column('parking_records', sa.Column('helmet_charge', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_parking_records_admin_id'), 'parking_records', ['admin_id'], unique=False)
    op.create_index(op.f('ix_parking_records_shift_id'), 'parking_records', ['shift_id'], unique=False)
    op.create_foreign_key(op.f('fk_parking_records_admin_id_operational_admins'), 'parking_records', 'operational_admins', ['admin_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_parking_records_shift_id_shifts'), 'parking_records', 'shifts', ['shift_id'], ['id'], ondelete='RESTRICT')

    # 5. Rates & Shifts & Vehicles & Vouchers & Washers (Defaults)
    op.alter_column('rates', 'rate_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('rates', 'price',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('shifts', 'shift_date',
               existing_type=sa.DATE(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('vehicles', 'owner_name',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               existing_nullable=False)
    op.alter_column('vouchers', 'voucher_number',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('vouchers', 'entity',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               existing_nullable=False)
    op.alter_column('vouchers', 'amount',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('vouchers', 'payment_date',
               existing_type=sa.DATE(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('washers', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               server_default=None,
               existing_nullable=False)
    op.alter_column('washers', 'full_name',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               existing_nullable=False)

    # 6. Washing Services
    op.add_column('washing_services', sa.Column('shift_id', sa.Integer(), nullable=True))
    op.add_column('washing_services', sa.Column('admin_id', sa.Integer(), nullable=True))
    
    op.execute("UPDATE washing_services SET shift_id = 1 WHERE shift_id IS NULL")
    op.execute("UPDATE washing_services SET admin_id = 1 WHERE admin_id IS NULL")
    
    op.alter_column('washing_services', 'shift_id', nullable=False)
    op.alter_column('washing_services', 'admin_id', nullable=False)
    
    op.alter_column('washing_services', 'service_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('washing_services', 'service_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('washing_services', 'price',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_washing_services_admin_id'), 'washing_services', ['admin_id'], unique=False)
    op.create_index(op.f('ix_washing_services_shift_id'), 'washing_services', ['shift_id'], unique=False)
    op.create_foreign_key(op.f('fk_washing_services_admin_id_operational_admins'), 'washing_services', 'operational_admins', ['admin_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_washing_services_shift_id_shifts'), 'washing_services', 'shifts', ['shift_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Revertir los cambios (rollback).
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_washing_services_shift_id_shifts'), 'washing_services', type_='foreignkey')
    op.drop_constraint(op.f('fk_washing_services_admin_id_operational_admins'), 'washing_services', type_='foreignkey')
    op.drop_index(op.f('ix_washing_services_shift_id'), table_name='washing_services')
    op.drop_index(op.f('ix_washing_services_admin_id'), table_name='washing_services')
    op.alter_column('washing_services', 'price',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('washing_services', 'service_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('washing_services', 'service_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'Basic'::character varying"),
               existing_nullable=False)
    op.drop_column('washing_services', 'admin_id')
    op.drop_column('washing_services', 'shift_id')
    op.alter_column('washers', 'full_name',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("'Washer'::character varying"),
               existing_nullable=False)
    op.alter_column('washers', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               server_default=sa.text("'hash'::character varying"),
               existing_nullable=False)
    op.alter_column('vouchers', 'payment_date',
               existing_type=sa.DATE(),
               server_default=sa.text("'2024-01-01'::date"),
               existing_nullable=False)
    op.alter_column('vouchers', 'amount',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('vouchers', 'entity',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("'Unknown'::character varying"),
               existing_nullable=False)
    op.alter_column('vouchers', 'voucher_number',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'000'::character varying"),
               existing_nullable=False)
    op.alter_column('vehicles', 'owner_name',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("'Unknown'::character varying"),
               existing_nullable=False)
    op.alter_column('shifts', 'shift_date',
               existing_type=sa.DATE(),
               server_default=sa.text("'2024-01-01'::date"),
               existing_nullable=False)
    op.alter_column('rates', 'price',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('rates', 'rate_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'Standard'::character varying"),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_parking_records_shift_id_shifts'), 'parking_records', type_='foreignkey')
    op.drop_constraint(op.f('fk_parking_records_admin_id_operational_admins'), 'parking_records', type_='foreignkey')
    op.drop_index(op.f('ix_parking_records_shift_id'), table_name='parking_records')
    op.drop_index(op.f('ix_parking_records_admin_id'), table_name='parking_records')
    op.drop_column('parking_records', 'helmet_charge')
    op.drop_column('parking_records', 'helmet_count')
    op.drop_column('parking_records', 'admin_id')
    op.drop_column('parking_records', 'shift_id')
    op.alter_column('operational_admins', 'full_name',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("'Admin'::character varying"),
               existing_nullable=False)
    op.alter_column('global_admins', 'full_name',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("'Admin'::character varying"),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_financial_reports_generated_by_global_admins'), 'financial_reports', type_='foreignkey')
    op.drop_constraint(op.f('fk_financial_reports_shift_id_shifts'), 'financial_reports', type_='foreignkey')
    op.drop_column('financial_reports', 'shift_id')
    op.drop_column('financial_reports', 'generated_by')
    op.drop_constraint(op.f('fk_business_config_updated_by_global_admins'), 'business_config', type_='foreignkey')
    op.drop_column('business_config', 'updated_by')
    # ### end Alembic commands ###
