"""add_start_end_time_to_washing_services

Revision ID: 68e02f84ead7
Revises: c1af9c27ed87
Create Date: 2025-11-26 23:16:33.298573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68e02f84ead7'
down_revision: Union[str, None] = 'c1af9c27ed87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Aplicar los cambios a la base de datos (migración hacia adelante).
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('washing_services', sa.Column('start_time', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('washing_services', sa.Column('end_time', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Revertir los cambios (rollback).
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('washing_services', 'end_time')
    op.drop_column('washing_services', 'start_time')
    # ### end Alembic commands ###
