"""update washers table

Revision ID: 786511d24a87
Revises: 8895265905aa
Create Date: 2025-11-26 06:05:42.917390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '786511d24a87'
down_revision: Union[str, None] = '8895265905aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Aplicar los cambios a la base de datos (migración hacia adelante).
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agreement_vehicles', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('agreement_vehicles', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('agreement_vehicles', 'agreement_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('agreement_vehicles', 'vehicle_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('agreement_vehicles_agreement_id_vehicle_id_key', 'agreement_vehicles', type_='unique')
    op.drop_index('idx_agreement_vehicles_agreement_id', table_name='agreement_vehicles')
    op.create_index(op.f('ix_agreement_vehicles_agreement_id'), 'agreement_vehicles', ['agreement_id'], unique=False)
    op.create_index(op.f('ix_agreement_vehicles_id'), 'agreement_vehicles', ['id'], unique=False)
    op.create_index('ix_agreement_vehicles_unique', 'agreement_vehicles', ['agreement_id', 'vehicle_id'], unique=True)
    op.create_index(op.f('ix_agreement_vehicles_vehicle_id'), 'agreement_vehicles', ['vehicle_id'], unique=False)
    op.drop_column('agreement_vehicles', 'added_at')
    op.add_column('agreements', sa.Column('special_rate', sa.Integer(), nullable=True))
    op.add_column('agreements', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('agreements', 'company_name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('agreements', 'contact_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('agreements', 'discount_percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               server_default=None,
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('agreements', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('agreements', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('agreements', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_agreements_company_name', table_name='agreements')
    op.create_index(op.f('ix_agreements_company_name'), 'agreements', ['company_name'], unique=False)
    op.create_index(op.f('ix_agreements_id'), 'agreements', ['id'], unique=False)
    op.create_index('ix_agreements_is_active', 'agreements', ['is_active'], unique=False)
    op.drop_constraint('agreements_created_by_fkey', 'agreements', type_='foreignkey')
    op.drop_column('agreements', 'payment_type')
    op.drop_column('agreements', 'created_by')
    op.add_column('audit_logs', sa.Column('entity_type', sa.String(length=50), nullable=True))
    op.add_column('audit_logs', sa.Column('entity_id', sa.Integer(), nullable=True))
    op.add_column('audit_logs', sa.Column('details', sa.Text(), nullable=True))
    op.add_column('audit_logs', sa.Column('timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index('idx_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('idx_audit_logs_user_type_id', table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index('ix_audit_logs_user', 'audit_logs', ['user_type', 'user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_type'), 'audit_logs', ['user_type'], unique=False)
    op.drop_column('audit_logs', 'created_at')
    op.drop_column('audit_logs', 'old_values')
    op.drop_column('audit_logs', 'table_name')
    op.drop_column('audit_logs', 'record_id')
    op.drop_column('audit_logs', 'new_values')
    op.add_column('bonuses', sa.Column('shift_id', sa.Integer(), nullable=True))
    op.add_column('bonuses', sa.Column('reason', sa.String(length=255), nullable=True))
    op.add_column('bonuses', sa.Column('bonus_date', sa.Date(), nullable=False))
    op.add_column('bonuses', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('bonuses', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('bonuses', 'washer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bonuses', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index('idx_bonuses_washer_id', table_name='bonuses')
    op.drop_index('idx_bonuses_washing_service_id', table_name='bonuses')
    op.create_index('ix_bonuses_bonus_date', 'bonuses', ['bonus_date'], unique=False)
    op.create_index(op.f('ix_bonuses_id'), 'bonuses', ['id'], unique=False)
    op.create_index(op.f('ix_bonuses_shift_id'), 'bonuses', ['shift_id'], unique=False)
    op.create_index('ix_bonuses_washer_date', 'bonuses', ['washer_id', 'bonus_date'], unique=False)
    op.create_index(op.f('ix_bonuses_washer_id'), 'bonuses', ['washer_id'], unique=False)
    op.drop_constraint('bonuses_washing_service_id_fkey', 'bonuses', type_='foreignkey')
    op.create_foreign_key(op.f('fk_bonuses_shift_id_shifts'), 'bonuses', 'shifts', ['shift_id'], ['id'], ondelete='CASCADE')
    op.drop_column('bonuses', 'washing_service_id')
    op.drop_column('bonuses', 'paid_at')
    op.drop_column('bonuses', 'notes')
    op.add_column('business_config', sa.Column('data_type', sa.String(length=20), nullable=True))
    op.add_column('business_config', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('business_config', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('business_config', 'config_value',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('business_config', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('business_config', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('business_config_config_key_key', 'business_config', type_='unique')
    op.create_index(op.f('ix_business_config_config_key'), 'business_config', ['config_key'], unique=True)
    op.create_index(op.f('ix_business_config_id'), 'business_config', ['id'], unique=False)
    op.drop_constraint('business_config_updated_by_fkey', 'business_config', type_='foreignkey')
    op.drop_column('business_config', 'updated_by')
    op.add_column('expenses', sa.Column('expense_type', sa.String(length=50), nullable=False))
    op.add_column('expenses', sa.Column('expense_date', sa.Date(), nullable=False))
    op.add_column('expenses', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('expenses', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('expenses', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('expenses', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_expenses_shift_id', table_name='expenses')
    op.create_index('ix_expenses_expense_date', 'expenses', ['expense_date'], unique=False)
    op.create_index('ix_expenses_expense_type', 'expenses', ['expense_type'], unique=False)
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.create_index(op.f('ix_expenses_shift_id'), 'expenses', ['shift_id'], unique=False)
    op.drop_constraint('expenses_created_by_fkey', 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'receipt_number')
    op.drop_column('expenses', 'created_by')
    op.drop_column('expenses', 'category')
    op.add_column('financial_reports', sa.Column('report_date', sa.TIMESTAMP(timezone=True), nullable=False))
    op.add_column('financial_reports', sa.Column('parking_count', sa.Integer(), nullable=True))
    op.add_column('financial_reports', sa.Column('subscription_count', sa.Integer(), nullable=True))
    op.add_column('financial_reports', sa.Column('report_data', sa.Text(), nullable=True))
    op.add_column('financial_reports', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('financial_reports', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('financial_reports', 'report_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('financial_reports', 'total_income',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('financial_reports', 'total_expenses',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('financial_reports', 'net_profit',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('financial_reports', 'washing_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.create_index(op.f('ix_financial_reports_id'), 'financial_reports', ['id'], unique=False)
    op.create_index(op.f('ix_financial_reports_report_date'), 'financial_reports', ['report_date'], unique=False)
    op.create_index(op.f('ix_financial_reports_report_type'), 'financial_reports', ['report_type'], unique=False)
    op.create_index('ix_financial_reports_type_date', 'financial_reports', ['report_type', 'report_date'], unique=False)
    op.drop_constraint('financial_reports_generated_by_fkey', 'financial_reports', type_='foreignkey')
    op.drop_column('financial_reports', 'generated_at')
    op.drop_column('financial_reports', 'generated_by')
    op.drop_column('financial_reports', 'start_date')
    op.drop_column('financial_reports', 'total_washing_income')
    op.drop_column('financial_reports', 'vehicle_count')
    op.drop_column('financial_reports', 'end_date')
    op.drop_column('financial_reports', 'total_parking_income')
    op.drop_column('financial_reports', 'total_bonuses')
    op.add_column('global_admins', sa.Column('full_name', sa.String(length=100), nullable=False, server_default='Admin'))
    op.add_column('global_admins', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('global_admins', sa.Column('last_login', sa.TIMESTAMP(timezone=True), nullable=True))
    op.alter_column('global_admins', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('global_admins', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('global_admins', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('global_admins_email_key', 'global_admins', type_='unique')
    op.drop_index('idx_global_admins_email', table_name='global_admins')
    op.create_index(op.f('ix_global_admins_email'), 'global_admins', ['email'], unique=True)
    op.create_index(op.f('ix_global_admins_id'), 'global_admins', ['id'], unique=False)
    op.create_index(op.f('ix_global_admins_is_active'), 'global_admins', ['is_active'], unique=False)
    op.drop_column('global_admins', 'name')
    op.add_column('monthly_subscriptions', sa.Column('monthly_fee', sa.Integer(), nullable=False))
    op.add_column('monthly_subscriptions', sa.Column('payment_status', sa.String(length=20), nullable=True))
    op.add_column('monthly_subscriptions', sa.Column('notes', sa.String(length=255), nullable=True))
    op.add_column('monthly_subscriptions', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('monthly_subscriptions', 'vehicle_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('monthly_subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index('ix_monthly_subscriptions_dates', 'monthly_subscriptions', ['start_date', 'end_date'], unique=False)
    op.create_index(op.f('ix_monthly_subscriptions_end_date'), 'monthly_subscriptions', ['end_date'], unique=False)
    op.create_index(op.f('ix_monthly_subscriptions_id'), 'monthly_subscriptions', ['id'], unique=False)
    op.create_index('ix_monthly_subscriptions_payment_status', 'monthly_subscriptions', ['payment_status'], unique=False)
    op.create_index(op.f('ix_monthly_subscriptions_start_date'), 'monthly_subscriptions', ['start_date'], unique=False)
    op.create_index(op.f('ix_monthly_subscriptions_vehicle_id'), 'monthly_subscriptions', ['vehicle_id'], unique=False)
    op.drop_constraint('monthly_subscriptions_created_by_fkey', 'monthly_subscriptions', type_='foreignkey')
    op.drop_column('monthly_subscriptions', 'vehicle_type')
    op.drop_column('monthly_subscriptions', 'is_active')
    op.drop_column('monthly_subscriptions', 'created_by')
    op.drop_column('monthly_subscriptions', 'monthly_rate')
    op.add_column('notifications', sa.Column('recipient_type', sa.String(length=50), nullable=False))
    op.add_column('notifications', sa.Column('recipient_id', sa.Integer(), nullable=False))
    op.alter_column('notifications', 'notification_type',
               existing_type=postgresql.ENUM('info', 'warning', 'error', 'success', name='notification_type'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('notifications', 'title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('notifications', 'read_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_notifications_is_read', table_name='notifications')
    op.drop_index('idx_notifications_user_type_id', table_name='notifications')
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index('ix_notifications_recipient', 'notifications', ['recipient_type', 'recipient_id'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_type'), 'notifications', ['recipient_type'], unique=False)
    op.drop_column('notifications', 'user_type')
    op.drop_column('notifications', 'user_id')
    op.add_column('operational_admins', sa.Column('full_name', sa.String(length=100), nullable=False, server_default='Admin'))
    op.add_column('operational_admins', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('operational_admins', sa.Column('last_login', sa.TIMESTAMP(timezone=True), nullable=True))
    op.alter_column('operational_admins', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('operational_admins', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('operational_admins', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_operational_admins_email', table_name='operational_admins')
    op.drop_constraint('operational_admins_email_key', 'operational_admins', type_='unique')
    op.create_index(op.f('ix_operational_admins_email'), 'operational_admins', ['email'], unique=True)
    op.create_index(op.f('ix_operational_admins_id'), 'operational_admins', ['id'], unique=False)
    op.create_index(op.f('ix_operational_admins_is_active'), 'operational_admins', ['is_active'], unique=False)
    op.drop_column('operational_admins', 'name')
    op.add_column('parking_records', sa.Column('parking_rate_id', sa.Integer(), nullable=False))
    op.add_column('parking_records', sa.Column('subscription_id', sa.Integer(), nullable=True))
    op.add_column('parking_records', sa.Column('total_cost', sa.Integer(), nullable=True))
    op.add_column('parking_records', sa.Column('payment_status', sa.String(length=20), nullable=True))
    op.add_column('parking_records', sa.Column('notes', sa.String(length=255), nullable=True))
    op.alter_column('parking_records', 'vehicle_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('parking_records', 'entry_time',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('parking_records', 'exit_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('parking_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('parking_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_parking_records_entry_time', table_name='parking_records')
    op.drop_index('idx_parking_records_exit_time', table_name='parking_records')
    op.drop_index('idx_parking_records_vehicle_id', table_name='parking_records')
    op.create_index('ix_parking_records_entry_time', 'parking_records', ['entry_time'], unique=False)
    op.create_index('ix_parking_records_exit_time', 'parking_records', ['exit_time'], unique=False)
    op.create_index(op.f('ix_parking_records_id'), 'parking_records', ['id'], unique=False)
    op.create_index('ix_parking_records_payment_status', 'parking_records', ['payment_status'], unique=False)
    op.create_index(op.f('ix_parking_records_vehicle_id'), 'parking_records', ['vehicle_id'], unique=False)
    op.drop_constraint('parking_records_closed_by_fkey', 'parking_records', type_='foreignkey')
    op.drop_constraint('parking_records_monthly_subscription_id_fkey', 'parking_records', type_='foreignkey')
    op.drop_constraint('parking_records_vehicle_id_fkey', 'parking_records', type_='foreignkey')
    op.drop_constraint('parking_records_agreement_id_fkey', 'parking_records', type_='foreignkey')
    op.drop_constraint('parking_records_created_by_fkey', 'parking_records', type_='foreignkey')
    op.drop_constraint('parking_records_washing_service_id_fkey', 'parking_records', type_='foreignkey')
    op.create_foreign_key(op.f('fk_parking_records_vehicle_id_vehicles'), 'parking_records', 'vehicles', ['vehicle_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_parking_records_parking_rate_id_rates'), 'parking_records', 'rates', ['parking_rate_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_parking_records_washing_service_id_washing_services'), 'parking_records', 'washing_services', ['washing_service_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_parking_records_subscription_id_monthly_subscriptions'), 'parking_records', 'monthly_subscriptions', ['subscription_id'], ['id'], ondelete='SET NULL')
    op.drop_column('parking_records', 'payment_method')
    op.drop_column('parking_records', 'paid_at')
    op.drop_column('parking_records', 'payment_type')
    op.drop_column('parking_records', 'created_by')
    op.drop_column('parking_records', 'exempt_minutes')
    op.drop_column('parking_records', 'subtotal')
    op.drop_column('parking_records', 'monthly_subscription_id')
    op.drop_column('parking_records', 'discount_amount')
    op.drop_column('parking_records', 'closed_by')
    op.drop_column('parking_records', 'total_amount')
    op.drop_column('parking_records', 'agreement_id')
    op.drop_column('parking_records', 'total_minutes')
    op.alter_column('password_reset_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('password_reset_tokens', 'is_used',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('password_reset_tokens', 'used_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('password_reset_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('password_reset_tokens_token_key', 'password_reset_tokens', type_='unique')
    op.create_index(op.f('ix_password_reset_tokens_expires_at'), 'password_reset_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_is_used'), 'password_reset_tokens', ['is_used'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_index('ix_password_reset_tokens_token_valid', 'password_reset_tokens', ['token', 'is_used', 'expires_at'], unique=False)
    op.create_index('ix_password_reset_tokens_user', 'password_reset_tokens', ['user_type', 'user_id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_user_type'), 'password_reset_tokens', ['user_type'], unique=False)
    op.add_column('rates', sa.Column('rate_type', sa.String(length=50), nullable=False, server_default='Standard'))
    op.add_column('rates', sa.Column('price', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('rates', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('rates', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('rates', 'vehicle_type',
               existing_type=postgresql.ENUM('carro', 'moto', 'camión', 'bicicleta', name='vehicle_type'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('rates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('rates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('rates_vehicle_type_key', 'rates', type_='unique')
    op.create_index(op.f('ix_rates_id'), 'rates', ['id'], unique=False)
    op.create_index(op.f('ix_rates_is_active'), 'rates', ['is_active'], unique=False)
    op.create_index(op.f('ix_rates_rate_type'), 'rates', ['rate_type'], unique=False)
    op.create_index(op.f('ix_rates_vehicle_type'), 'rates', ['vehicle_type'], unique=False)
    op.create_index('ix_rates_vehicle_type_rate_type', 'rates', ['vehicle_type', 'rate_type'], unique=False)
    op.drop_column('rates', 'completo_free_minutes')
    op.drop_column('rates', 'basico_free_minutes')
    op.drop_column('rates', 'parking_rate_per_minute')
    op.drop_column('rates', 'wash_moto')
    op.drop_column('rates', 'helmet_fee')
    op.drop_column('rates', 'wash_basico')
    op.drop_column('rates', 'wash_completo')
    op.drop_column('rates', 'wash_especial')
    op.drop_column('rates', 'especial_free_minutes')
    op.drop_column('rates', 'wash_lujo')
    op.drop_column('rates', 'parking_flat_rate')
    op.drop_column('rates', 'lujo_free_minutes')
    op.drop_column('rates', 'moto_free_minutes')
    op.add_column('shifts', sa.Column('shift_date', sa.Date(), nullable=False, server_default='2024-01-01'))
    op.add_column('shifts', sa.Column('initial_cash', sa.Integer(), nullable=True))
    op.add_column('shifts', sa.Column('final_cash', sa.Integer(), nullable=True))
    op.add_column('shifts', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('shifts', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('shifts', 'admin_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('shifts', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('shifts', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('shifts', 'total_income',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('shifts', 'total_expenses',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('shifts', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index('idx_shifts_admin_id', table_name='shifts')
    op.drop_index('idx_shifts_start_time', table_name='shifts')
    op.create_index('ix_shifts_admin_date', 'shifts', ['admin_id', 'shift_date'], unique=False)
    op.create_index(op.f('ix_shifts_admin_id'), 'shifts', ['admin_id'], unique=False)
    op.create_index(op.f('ix_shifts_id'), 'shifts', ['id'], unique=False)
    op.create_index('ix_shifts_shift_date', 'shifts', ['shift_date'], unique=False)
    op.drop_constraint('shifts_admin_id_fkey', 'shifts', type_='foreignkey')
    op.create_foreign_key(op.f('fk_shifts_admin_id_operational_admins'), 'shifts', 'operational_admins', ['admin_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('shifts', 'discrepancy')
    op.drop_column('shifts', 'total_washing_income')
    op.drop_column('shifts', 'card_total')
    op.drop_column('shifts', 'is_closed')
    op.drop_column('shifts', 'transfer_total')
    op.drop_column('shifts', 'cash_count')
    op.drop_column('shifts', 'total_parking_income')
    op.drop_column('shifts', 'closed_at')
    op.add_column('vehicles', sa.Column('brand', sa.String(length=50), nullable=True))
    op.add_column('vehicles', sa.Column('model', sa.String(length=50), nullable=True))
    op.add_column('vehicles', sa.Column('color', sa.String(length=50), nullable=True))
    op.add_column('vehicles', sa.Column('is_frequent', sa.Boolean(), nullable=True))
    op.alter_column('vehicles', 'owner_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False, server_default='Unknown')
    op.alter_column('vehicles', 'vehicle_type',
               existing_type=postgresql.ENUM('carro', 'moto', 'camión', 'bicicleta', name='vehicle_type'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('vehicles', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('vehicles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('vehicles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_vehicles_plate', table_name='vehicles')
    op.drop_constraint('vehicles_plate_key', 'vehicles', type_='unique')
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_index('ix_vehicles_is_frequent', 'vehicles', ['is_frequent'], unique=False)
    op.create_index('ix_vehicles_owner_name', 'vehicles', ['owner_name'], unique=False)
    op.create_index(op.f('ix_vehicles_plate'), 'vehicles', ['plate'], unique=True)
    op.create_index('ix_vehicles_vehicle_type', 'vehicles', ['vehicle_type'], unique=False)
    op.add_column('vouchers', sa.Column('voucher_number', sa.String(length=50), nullable=False, server_default='000'))
    op.add_column('vouchers', sa.Column('entity', sa.String(length=100), nullable=False, server_default='Unknown'))
    op.add_column('vouchers', sa.Column('amount', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('vouchers', sa.Column('payment_date', sa.Date(), nullable=False, server_default='2024-01-01'))
    op.add_column('vouchers', sa.Column('reference_number', sa.String(length=100), nullable=True))
    op.add_column('vouchers', sa.Column('notes', sa.String(length=255), nullable=True))
    op.add_column('vouchers', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('vouchers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('vouchers_code_key', 'vouchers', type_='unique')
    op.create_index('ix_vouchers_entity', 'vouchers', ['entity'], unique=False)
    op.create_index(op.f('ix_vouchers_id'), 'vouchers', ['id'], unique=False)
    op.create_index(op.f('ix_vouchers_payment_date'), 'vouchers', ['payment_date'], unique=False)
    op.create_index(op.f('ix_vouchers_voucher_number'), 'vouchers', ['voucher_number'], unique=True)
    op.drop_constraint('vouchers_parking_record_id_fkey', 'vouchers', type_='foreignkey')
    op.drop_constraint('vouchers_created_by_fkey', 'vouchers', type_='foreignkey')
    op.drop_column('vouchers', 'code')
    op.drop_column('vouchers', 'discount_type')
    op.drop_column('vouchers', 'used_date')
    op.drop_column('vouchers', 'issue_date')
    op.drop_column('vouchers', 'created_by')
    op.drop_column('vouchers', 'is_used')
    op.drop_column('vouchers', 'discount_amount')
    op.drop_column('vouchers', 'employee_name')
    op.drop_column('vouchers', 'parking_record_id')
    op.add_column('washers', sa.Column('password_hash', sa.String(length=255), nullable=False, server_default='hash'))
    op.add_column('washers', sa.Column('full_name', sa.String(length=100), nullable=False, server_default='Washer'))
    op.add_column('washers', sa.Column('commission_percentage', sa.Integer(), nullable=True))
    op.add_column('washers', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('washers', sa.Column('last_login', sa.TIMESTAMP(timezone=True), nullable=True))
    op.alter_column('washers', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('washers', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('washers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_washers_email', table_name='washers')
    op.drop_constraint('washers_email_key', 'washers', type_='unique')
    op.create_index(op.f('ix_washers_email'), 'washers', ['email'], unique=True)
    op.create_index(op.f('ix_washers_id'), 'washers', ['id'], unique=False)
    op.create_index(op.f('ix_washers_is_active'), 'washers', ['is_active'], unique=False)
    op.drop_column('washers', 'name')
    op.drop_column('washers', 'total_bonuses')
    op.add_column('washing_services', sa.Column('washer_id', sa.Integer(), nullable=True))
    op.add_column('washing_services', sa.Column('service_type', sa.String(length=50), nullable=False, server_default='Basic'))
    op.add_column('washing_services', sa.Column('service_date', sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text('now()')))
    op.add_column('washing_services', sa.Column('price', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('washing_services', sa.Column('payment_status', sa.String(length=20), nullable=True))
    op.add_column('washing_services', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('washing_services', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('washing_services', 'vehicle_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('washing_services', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index('idx_washing_services_status', table_name='washing_services')
    op.drop_index('idx_washing_services_vehicle_id', table_name='washing_services')
    op.drop_index('idx_washing_services_washer1', table_name='washing_services')
    op.create_index(op.f('ix_washing_services_id'), 'washing_services', ['id'], unique=False)
    op.create_index('ix_washing_services_payment_status', 'washing_services', ['payment_status'], unique=False)
    op.create_index(op.f('ix_washing_services_service_date'), 'washing_services', ['service_date'], unique=False)
    op.create_index(op.f('ix_washing_services_vehicle_id'), 'washing_services', ['vehicle_id'], unique=False)
    op.create_unique_constraint(op.f('uq_washing_services_parking_record_id'), 'washing_services', ['parking_record_id'])
    op.drop_constraint('washing_services_agreement_id_fkey', 'washing_services', type_='foreignkey')
    op.drop_constraint('washing_services_vehicle_id_fkey', 'washing_services', type_='foreignkey')
    op.drop_constraint('washing_services_created_by_fkey', 'washing_services', type_='foreignkey')
    op.drop_constraint('fk_washing_parking', 'washing_services', type_='foreignkey')
    op.drop_constraint('washing_services_approved_by_fkey', 'washing_services', type_='foreignkey')
    op.drop_constraint('washing_services_washer1_id_fkey', 'washing_services', type_='foreignkey')
    op.create_foreign_key(op.f('fk_washing_services_vehicle_id_vehicles'), 'washing_services', 'vehicles', ['vehicle_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_washing_services_parking_record_id_parking_records'), 'washing_services', 'parking_records', ['parking_record_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_washing_services_washer_id_washers'), 'washing_services', 'washers', ['washer_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('washing_services', 'created_by')
    op.drop_column('washing_services', 'completed_at')
    op.drop_column('washing_services', 'agreement_id')
    op.drop_column('washing_services', 'requires_approval')
    op.drop_column('washing_services', 'service_status')
    op.drop_column('washing_services', 'approved_at')
    op.drop_column('washing_services', 'bonus_percentage')
    op.drop_column('washing_services', 'net_amount')
    op.drop_column('washing_services', 'approved_by')
    op.drop_column('washing_services', 'service_category')
    op.drop_column('washing_services', 'helmet_fee')
    op.drop_column('washing_services', 'washer1_id')
    op.drop_column('washing_services', 'bonus_per_washer')
    op.drop_column('washing_services', 'started_at')
    op.drop_column('washing_services', 'requested_at')
    op.drop_column('washing_services', 'service_price')
    op.drop_column('washing_services', 'helmet_count')
    op.drop_column('washing_services', 'total_bonus')
    op.drop_column('washing_services', 'discount_amount')
    op.drop_column('washing_services', 'washer2_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Revertir los cambios (rollback).
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('washing_services', sa.Column('washer2_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('washing_services', sa.Column('discount_amount', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True))
    op.add_column('washing_services', sa.Column('total_bonus', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True))
    op.add_column('washing_services', sa.Column('helmet_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('washing_services', sa.Column('service_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('washing_services', sa.Column('requested_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('washing_services', sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('washing_services', sa.Column('bonus_per_washer', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True))
    op.add_column('washing_services', sa.Column('washer1_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('washing_services', sa.Column('helmet_fee', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True))
    op.add_column('washing_services', sa.Column('service_category', postgresql.ENUM('basico', 'especial', 'completo', 'lujo', 'moto', name='service_category'), autoincrement=False, nullable=False))
    op.add_column('washing_services', sa.Column('approved_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('washing_services', sa.Column('net_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('washing_services', sa.Column('bonus_percentage', sa.NUMERIC(precision=5, scale=2), server_default=sa.text('15.00'), autoincrement=False, nullable=True))
    op.add_column('washing_services', sa.Column('approved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('washing_services', sa.Column('service_status', postgresql.ENUM('pendiente', 'en_proceso', 'completado', 'cancelado', name='service_status'), server_default=sa.text("'pendiente'::service_status"), autoincrement=False, nullable=True))
    op.add_column('washing_services', sa.Column('requires_approval', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('washing_services', sa.Column('agreement_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('washing_services', sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('washing_services', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_washing_services_washer_id_washers'), 'washing_services', type_='foreignkey')
    op.drop_constraint(op.f('fk_washing_services_parking_record_id_parking_records'), 'washing_services', type_='foreignkey')
    op.drop_constraint(op.f('fk_washing_services_vehicle_id_vehicles'), 'washing_services', type_='foreignkey')
    op.create_foreign_key('washing_services_washer1_id_fkey', 'washing_services', 'washers', ['washer1_id'], ['id'])
    op.create_foreign_key('washing_services_approved_by_fkey', 'washing_services', 'global_admins', ['approved_by'], ['id'])
    op.create_foreign_key('fk_washing_parking', 'washing_services', 'parking_records', ['parking_record_id'], ['id'])
    op.create_foreign_key('washing_services_created_by_fkey', 'washing_services', 'operational_admins', ['created_by'], ['id'])
    op.create_foreign_key('washing_services_vehicle_id_fkey', 'washing_services', 'vehicles', ['vehicle_id'], ['id'])
    op.create_foreign_key('washing_services_agreement_id_fkey', 'washing_services', 'agreements', ['agreement_id'], ['id'])
    op.drop_constraint(op.f('uq_washing_services_parking_record_id'), 'washing_services', type_='unique')
    op.drop_index(op.f('ix_washing_services_vehicle_id'), table_name='washing_services')
    op.drop_index(op.f('ix_washing_services_service_date'), table_name='washing_services')
    op.drop_index('ix_washing_services_payment_status', table_name='washing_services')
    op.drop_index(op.f('ix_washing_services_id'), table_name='washing_services')
    op.create_index('idx_washing_services_washer1', 'washing_services', ['washer1_id'], unique=False)
    op.create_index('idx_washing_services_vehicle_id', 'washing_services', ['vehicle_id'], unique=False)
    op.create_index('idx_washing_services_status', 'washing_services', ['service_status'], unique=False)
    op.alter_column('washing_services', 'notes',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('washing_services', 'vehicle_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('washing_services', 'updated_at')
    op.drop_column('washing_services', 'created_at')
    op.drop_column('washing_services', 'payment_status')
    op.drop_column('washing_services', 'price')
    op.drop_column('washing_services', 'service_date')
    op.drop_column('washing_services', 'service_type')
    op.drop_column('washing_services', 'washer_id')
    op.add_column('washers', sa.Column('total_bonuses', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True))
    op.add_column('washers', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_washers_is_active'), table_name='washers')
    op.drop_index(op.f('ix_washers_id'), table_name='washers')
    op.drop_index(op.f('ix_washers_email'), table_name='washers')
    op.create_unique_constraint('washers_email_key', 'washers', ['email'])
    op.create_index('idx_washers_email', 'washers', ['email'], unique=False)
    op.alter_column('washers', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('washers', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('washers', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('washers', 'last_login')
    op.drop_column('washers', 'updated_at')
    op.drop_column('washers', 'commission_percentage')
    op.drop_column('washers', 'full_name')
    op.drop_column('washers', 'password_hash')
    op.add_column('vouchers', sa.Column('parking_record_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('vouchers', sa.Column('employee_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('vouchers', sa.Column('discount_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('vouchers', sa.Column('is_used', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('vouchers', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('vouchers', sa.Column('issue_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('vouchers', sa.Column('used_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('vouchers', sa.Column('discount_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('vouchers', sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_foreign_key('vouchers_created_by_fkey', 'vouchers', 'global_admins', ['created_by'], ['id'])
    op.create_foreign_key('vouchers_parking_record_id_fkey', 'vouchers', 'parking_records', ['parking_record_id'], ['id'])
    op.drop_index(op.f('ix_vouchers_voucher_number'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_payment_date'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_id'), table_name='vouchers')
    op.drop_index('ix_vouchers_entity', table_name='vouchers')
    op.create_unique_constraint('vouchers_code_key', 'vouchers', ['code'])
    op.alter_column('vouchers', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('vouchers', 'updated_at')
    op.drop_column('vouchers', 'notes')
    op.drop_column('vouchers', 'reference_number')
    op.drop_column('vouchers', 'payment_date')
    op.drop_column('vouchers', 'amount')
    op.drop_column('vouchers', 'entity')
    op.drop_column('vouchers', 'voucher_number')
    op.drop_index('ix_vehicles_vehicle_type', table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_plate'), table_name='vehicles')
    op.drop_index('ix_vehicles_owner_name', table_name='vehicles')
    op.drop_index('ix_vehicles_is_frequent', table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.create_unique_constraint('vehicles_plate_key', 'vehicles', ['plate'])
    op.create_index('idx_vehicles_plate', 'vehicles', ['plate'], unique=False)
    op.alter_column('vehicles', 'updated_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('vehicles', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('vehicles', 'notes',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('vehicles', 'vehicle_type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('carro', 'moto', 'camión', 'bicicleta', name='vehicle_type'),
               existing_nullable=False)
    op.alter_column('vehicles', 'owner_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('vehicles', 'is_frequent')
    op.drop_column('vehicles', 'color')
    op.drop_column('vehicles', 'model')
    op.drop_column('vehicles', 'brand')
    op.add_column('shifts', sa.Column('closed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('shifts', sa.Column('total_parking_income', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True))
    op.add_column('shifts', sa.Column('cash_count', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('shifts', sa.Column('transfer_total', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('shifts', sa.Column('is_closed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('shifts', sa.Column('card_total', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('shifts', sa.Column('total_washing_income', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True))
    op.add_column('shifts', sa.Column('discrepancy', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_shifts_admin_id_operational_admins'), 'shifts', type_='foreignkey')
    op.create_foreign_key('shifts_admin_id_fkey', 'shifts', 'operational_admins', ['admin_id'], ['id'])
    op.drop_index('ix_shifts_shift_date', table_name='shifts')
    op.drop_index(op.f('ix_shifts_id'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_admin_id'), table_name='shifts')
    op.drop_index('ix_shifts_admin_date', table_name='shifts')
    op.create_index('idx_shifts_start_time', 'shifts', ['start_time'], unique=False)
    op.create_index('idx_shifts_admin_id', 'shifts', ['admin_id'], unique=False)
    op.alter_column('shifts', 'notes',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('shifts', 'total_expenses',
               existing_type=sa.Integer(),
               server_default=sa.text('0.00'),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('shifts', 'total_income',
               existing_type=sa.Integer(),
               server_default=sa.text('0.00'),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('shifts', 'end_time',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('shifts', 'start_time',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('shifts', 'admin_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('shifts', 'updated_at')
    op.drop_column('shifts', 'created_at')
    op.drop_column('shifts', 'final_cash')
    op.drop_column('shifts', 'initial_cash')
    op.drop_column('shifts', 'shift_date')
    op.add_column('rates', sa.Column('moto_free_minutes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('rates', sa.Column('lujo_free_minutes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('rates', sa.Column('parking_flat_rate', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('rates', sa.Column('wash_lujo', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('rates', sa.Column('especial_free_minutes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('rates', sa.Column('wash_especial', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('rates', sa.Column('wash_completo', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('rates', sa.Column('wash_basico', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('rates', sa.Column('helmet_fee', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True))
    op.add_column('rates', sa.Column('wash_moto', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('rates', sa.Column('parking_rate_per_minute', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('rates', sa.Column('basico_free_minutes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('rates', sa.Column('completo_free_minutes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.drop_index('ix_rates_vehicle_type_rate_type', table_name='rates')
    op.drop_index(op.f('ix_rates_vehicle_type'), table_name='rates')
    op.drop_index(op.f('ix_rates_rate_type'), table_name='rates')
    op.drop_index(op.f('ix_rates_is_active'), table_name='rates')
    op.drop_index(op.f('ix_rates_id'), table_name='rates')
    op.create_unique_constraint('rates_vehicle_type_key', 'rates', ['vehicle_type'])
    op.alter_column('rates', 'updated_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('rates', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('rates', 'vehicle_type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('carro', 'moto', 'camión', 'bicicleta', name='vehicle_type'),
               existing_nullable=False)
    op.drop_column('rates', 'is_active')
    op.drop_column('rates', 'description')
    op.drop_column('rates', 'price')
    op.drop_column('rates', 'rate_type')
    op.drop_index(op.f('ix_password_reset_tokens_user_type'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index('ix_password_reset_tokens_user', table_name='password_reset_tokens')
    op.drop_index('ix_password_reset_tokens_token_valid', table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_is_used'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_expires_at'), table_name='password_reset_tokens')
    op.create_unique_constraint('password_reset_tokens_token_key', 'password_reset_tokens', ['token'])
    op.alter_column('password_reset_tokens', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('password_reset_tokens', 'used_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('password_reset_tokens', 'is_used',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('password_reset_tokens', 'expires_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.add_column('parking_records', sa.Column('total_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('parking_records', sa.Column('agreement_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('parking_records', sa.Column('total_amount', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True))
    op.add_column('parking_records', sa.Column('closed_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('parking_records', sa.Column('discount_amount', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True))
    op.add_column('parking_records', sa.Column('monthly_subscription_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('parking_records', sa.Column('subtotal', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True))
    op.add_column('parking_records', sa.Column('exempt_minutes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('parking_records', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('parking_records', sa.Column('payment_type', postgresql.ENUM('minuto', 'plano', name='payment_type'), autoincrement=False, nullable=True))
    op.add_column('parking_records', sa.Column('paid_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('parking_records', sa.Column('payment_method', postgresql.ENUM('efectivo', 'tarjeta', 'transferencia', name='payment_method'), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_parking_records_subscription_id_monthly_subscriptions'), 'parking_records', type_='foreignkey')
    op.drop_constraint(op.f('fk_parking_records_washing_service_id_washing_services'), 'parking_records', type_='foreignkey')
    op.drop_constraint(op.f('fk_parking_records_parking_rate_id_rates'), 'parking_records', type_='foreignkey')
    op.drop_constraint(op.f('fk_parking_records_vehicle_id_vehicles'), 'parking_records', type_='foreignkey')
    op.create_foreign_key('parking_records_washing_service_id_fkey', 'parking_records', 'washing_services', ['washing_service_id'], ['id'])
    op.create_foreign_key('parking_records_created_by_fkey', 'parking_records', 'operational_admins', ['created_by'], ['id'])
    op.create_foreign_key('parking_records_agreement_id_fkey', 'parking_records', 'agreements', ['agreement_id'], ['id'])
    op.create_foreign_key('parking_records_vehicle_id_fkey', 'parking_records', 'vehicles', ['vehicle_id'], ['id'])
    op.create_foreign_key('parking_records_monthly_subscription_id_fkey', 'parking_records', 'monthly_subscriptions', ['monthly_subscription_id'], ['id'])
    op.create_foreign_key('parking_records_closed_by_fkey', 'parking_records', 'operational_admins', ['closed_by'], ['id'])
    op.drop_index(op.f('ix_parking_records_vehicle_id'), table_name='parking_records')
    op.drop_index('ix_parking_records_payment_status', table_name='parking_records')
    op.drop_index(op.f('ix_parking_records_id'), table_name='parking_records')
    op.drop_index('ix_parking_records_exit_time', table_name='parking_records')
    op.drop_index('ix_parking_records_entry_time', table_name='parking_records')
    op.create_index('idx_parking_records_vehicle_id', 'parking_records', ['vehicle_id'], unique=False)
    op.create_index('idx_parking_records_exit_time', 'parking_records', ['exit_time'], unique=False)
    op.create_index('idx_parking_records_entry_time', 'parking_records', ['entry_time'], unique=False)
    op.alter_column('parking_records', 'updated_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('parking_records', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('parking_records', 'exit_time',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('parking_records', 'entry_time',
               existing_type=sa.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('parking_records', 'vehicle_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('parking_records', 'notes')
    op.drop_column('parking_records', 'payment_status')
    op.drop_column('parking_records', 'total_cost')
    op.drop_column('parking_records', 'subscription_id')
    op.drop_column('parking_records', 'parking_rate_id')
    op.add_column('operational_admins', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_operational_admins_is_active'), table_name='operational_admins')
    op.drop_index(op.f('ix_operational_admins_id'), table_name='operational_admins')
    op.drop_index(op.f('ix_operational_admins_email'), table_name='operational_admins')
    op.create_unique_constraint('operational_admins_email_key', 'operational_admins', ['email'])
    op.create_index('idx_operational_admins_email', 'operational_admins', ['email'], unique=False)
    op.alter_column('operational_admins', 'updated_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('operational_admins', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('operational_admins', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.drop_column('operational_admins', 'last_login')
    op.drop_column('operational_admins', 'phone')
    op.drop_column('operational_admins', 'full_name')
    op.add_column('notifications', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('user_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_notifications_recipient_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    op.drop_index('ix_notifications_recipient', table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.create_index('idx_notifications_user_type_id', 'notifications', ['user_type', 'user_id'], unique=False)
    op.create_index('idx_notifications_is_read', 'notifications', ['is_read'], unique=False)
    op.alter_column('notifications', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('notifications', 'read_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('notifications', 'title',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('notifications', 'notification_type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('info', 'warning', 'error', 'success', name='notification_type'),
               existing_nullable=False)
    op.drop_column('notifications', 'recipient_id')
    op.drop_column('notifications', 'recipient_type')
    op.add_column('monthly_subscriptions', sa.Column('monthly_rate', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('monthly_subscriptions', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('monthly_subscriptions', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.add_column('monthly_subscriptions', sa.Column('vehicle_type', postgresql.ENUM('carro', 'moto', 'camión', 'bicicleta', name='vehicle_type'), autoincrement=False, nullable=False))
    op.create_foreign_key('monthly_subscriptions_created_by_fkey', 'monthly_subscriptions', 'global_admins', ['created_by'], ['id'])
    op.drop_index(op.f('ix_monthly_subscriptions_vehicle_id'), table_name='monthly_subscriptions')
    op.drop_index(op.f('ix_monthly_subscriptions_start_date'), table_name='monthly_subscriptions')
    op.drop_index('ix_monthly_subscriptions_payment_status', table_name='monthly_subscriptions')
    op.drop_index(op.f('ix_monthly_subscriptions_id'), table_name='monthly_subscriptions')
    op.drop_index(op.f('ix_monthly_subscriptions_end_date'), table_name='monthly_subscriptions')
    op.drop_index('ix_monthly_subscriptions_dates', table_name='monthly_subscriptions')
    op.alter_column('monthly_subscriptions', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('monthly_subscriptions', 'vehicle_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('monthly_subscriptions', 'updated_at')
    op.drop_column('monthly_subscriptions', 'notes')
    op.drop_column('monthly_subscriptions', 'payment_status')
    op.drop_column('monthly_subscriptions', 'monthly_fee')
    op.add_column('global_admins', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_global_admins_is_active'), table_name='global_admins')
    op.drop_index(op.f('ix_global_admins_id'), table_name='global_admins')
    op.drop_index(op.f('ix_global_admins_email'), table_name='global_admins')
    op.create_index('idx_global_admins_email', 'global_admins', ['email'], unique=False)
    op.create_unique_constraint('global_admins_email_key', 'global_admins', ['email'])
    op.alter_column('global_admins', 'updated_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('global_admins', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('global_admins', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.drop_column('global_admins', 'last_login')
    op.drop_column('global_admins', 'phone')
    op.drop_column('global_admins', 'full_name')
    op.add_column('financial_reports', sa.Column('total_bonuses', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True))
    op.add_column('financial_reports', sa.Column('total_parking_income', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True))
    op.add_column('financial_reports', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('financial_reports', sa.Column('vehicle_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('financial_reports', sa.Column('total_washing_income', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True))
    op.add_column('financial_reports', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('financial_reports', sa.Column('generated_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('financial_reports', sa.Column('generated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.create_foreign_key('financial_reports_generated_by_fkey', 'financial_reports', 'global_admins', ['generated_by'], ['id'])
    op.drop_index('ix_financial_reports_type_date', table_name='financial_reports')
    op.drop_index(op.f('ix_financial_reports_report_type'), table_name='financial_reports')
    op.drop_index(op.f('ix_financial_reports_report_date'), table_name='financial_reports')
    op.drop_index(op.f('ix_financial_reports_id'), table_name='financial_reports')
    op.alter_column('financial_reports', 'washing_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('financial_reports', 'net_profit',
               existing_type=sa.Integer(),
               server_default=sa.text('0.00'),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('financial_reports', 'total_expenses',
               existing_type=sa.Integer(),
               server_default=sa.text('0.00'),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('financial_reports', 'total_income',
               existing_type=sa.Integer(),
               server_default=sa.text('0.00'),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('financial_reports', 'report_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('financial_reports', 'updated_at')
    op.drop_column('financial_reports', 'created_at')
    op.drop_column('financial_reports', 'report_data')
    op.drop_column('financial_reports', 'subscription_count')
    op.drop_column('financial_reports', 'parking_count')
    op.drop_column('financial_reports', 'report_date')
    op.add_column('expenses', sa.Column('category', postgresql.ENUM('insumos', 'servicios', 'mantenimiento', 'otros', name='expense_category'), autoincrement=False, nullable=False))
    op.add_column('expenses', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('expenses', sa.Column('receipt_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_foreign_key('expenses_created_by_fkey', 'expenses', 'operational_admins', ['created_by'], ['id'])
    op.drop_index(op.f('ix_expenses_shift_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.drop_index('ix_expenses_expense_type', table_name='expenses')
    op.drop_index('ix_expenses_expense_date', table_name='expenses')
    op.create_index('idx_expenses_shift_id', 'expenses', ['shift_id'], unique=False)
    op.alter_column('expenses', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('expenses', 'description',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('expenses', 'amount',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_column('expenses', 'updated_at')
    op.drop_column('expenses', 'expense_date')
    op.drop_column('expenses', 'expense_type')
    op.add_column('business_config', sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('business_config_updated_by_fkey', 'business_config', 'global_admins', ['updated_by'], ['id'])
    op.drop_index(op.f('ix_business_config_id'), table_name='business_config')
    op.drop_index(op.f('ix_business_config_config_key'), table_name='business_config')
    op.create_unique_constraint('business_config_config_key_key', 'business_config', ['config_key'])
    op.alter_column('business_config', 'updated_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('business_config', 'description',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('business_config', 'config_value',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('business_config', 'created_at')
    op.drop_column('business_config', 'is_active')
    op.drop_column('business_config', 'data_type')
    op.add_column('bonuses', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('bonuses', sa.Column('paid_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('bonuses', sa.Column('washing_service_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_bonuses_shift_id_shifts'), 'bonuses', type_='foreignkey')
    op.create_foreign_key('bonuses_washing_service_id_fkey', 'bonuses', 'washing_services', ['washing_service_id'], ['id'])
    op.drop_index(op.f('ix_bonuses_washer_id'), table_name='bonuses')
    op.drop_index('ix_bonuses_washer_date', table_name='bonuses')
    op.drop_index(op.f('ix_bonuses_shift_id'), table_name='bonuses')
    op.drop_index(op.f('ix_bonuses_id'), table_name='bonuses')
    op.drop_index('ix_bonuses_bonus_date', table_name='bonuses')
    op.create_index('idx_bonuses_washing_service_id', 'bonuses', ['washing_service_id'], unique=False)
    op.create_index('idx_bonuses_washer_id', 'bonuses', ['washer_id'], unique=False)
    op.alter_column('bonuses', 'amount',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('bonuses', 'washer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('bonuses', 'updated_at')
    op.drop_column('bonuses', 'created_at')
    op.drop_column('bonuses', 'bonus_date')
    op.drop_column('bonuses', 'reason')
    op.drop_column('bonuses', 'shift_id')
    op.add_column('audit_logs', sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('record_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('table_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_audit_logs_user_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_user', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.create_index('idx_audit_logs_user_type_id', 'audit_logs', ['user_type', 'user_id'], unique=False)
    op.create_index('idx_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.drop_column('audit_logs', 'timestamp')
    op.drop_column('audit_logs', 'details')
    op.drop_column('audit_logs', 'entity_id')
    op.drop_column('audit_logs', 'entity_type')
    op.add_column('agreements', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('agreements', sa.Column('payment_type', postgresql.ENUM('prepago', 'postpago', name='agreement_payment_type'), autoincrement=False, nullable=False))
    op.create_foreign_key('agreements_created_by_fkey', 'agreements', 'global_admins', ['created_by'], ['id'])
    op.drop_index('ix_agreements_is_active', table_name='agreements')
    op.drop_index(op.f('ix_agreements_id'), table_name='agreements')
    op.drop_index(op.f('ix_agreements_company_name'), table_name='agreements')
    op.create_index('idx_agreements_company_name', 'agreements', ['company_name'], unique=False)
    op.alter_column('agreements', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('agreements', 'notes',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('agreements', 'is_active',
               existing_type=sa.String(length=20),
               server_default=sa.text('true'),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.alter_column('agreements', 'discount_percentage',
               existing_type=sa.Integer(),
               server_default=sa.text('0.00'),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('agreements', 'contact_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('agreements', 'company_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_column('agreements', 'updated_at')
    op.drop_column('agreements', 'special_rate')
    op.add_column('agreement_vehicles', sa.Column('added_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_agreement_vehicles_vehicle_id'), table_name='agreement_vehicles')
    op.drop_index('ix_agreement_vehicles_unique', table_name='agreement_vehicles')
    op.drop_index(op.f('ix_agreement_vehicles_id'), table_name='agreement_vehicles')
    op.drop_index(op.f('ix_agreement_vehicles_agreement_id'), table_name='agreement_vehicles')
    op.create_index('idx_agreement_vehicles_agreement_id', 'agreement_vehicles', ['agreement_id'], unique=False)
    op.create_unique_constraint('agreement_vehicles_agreement_id_vehicle_id_key', 'agreement_vehicles', ['agreement_id', 'vehicle_id'])
    op.alter_column('agreement_vehicles', 'vehicle_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('agreement_vehicles', 'agreement_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('agreement_vehicles', 'updated_at')
    op.drop_column('agreement_vehicles', 'created_at')
    # ### end Alembic commands ###
