"""initial_schema_complete

Revision ID: c1af9c27ed87
Revises: 
Create Date: 2025-11-26 21:35:07.060714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1af9c27ed87'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Aplicar los cambios a la base de datos (migración hacia adelante).
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agreements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('contact_name', sa.String(length=100), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('discount_percentage', sa.Integer(), nullable=True),
    sa.Column('special_rate', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("is_active IN ('active', 'inactive', 'expired')", name=op.f('ck_agreements_check_agreements_is_active_valid')),
    sa.CheckConstraint('discount_percentage >= 0 AND discount_percentage <= 100', name=op.f('ck_agreements_check_agreements_discount_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agreements'))
    )
    op.create_index(op.f('ix_agreements_company_name'), 'agreements', ['company_name'], unique=False)
    op.create_index(op.f('ix_agreements_id'), 'agreements', ['id'], unique=False)
    op.create_index('ix_agreements_is_active', 'agreements', ['is_active'], unique=False)
    
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_type', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index('ix_audit_logs_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_index('ix_audit_logs_user', 'audit_logs', ['user_type', 'user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_type'), 'audit_logs', ['user_type'], unique=False)
    
    op.create_table('global_admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_global_admins'))
    )
    op.create_index(op.f('ix_global_admins_email'), 'global_admins', ['email'], unique=True)
    op.create_index(op.f('ix_global_admins_id'), 'global_admins', ['id'], unique=False)
    op.create_index(op.f('ix_global_admins_is_active'), 'global_admins', ['is_active'], unique=False)
    
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_type', sa.String(length=50), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("notification_type IN ('alert', 'warning', 'info', 'success')", name=op.f('ck_notifications_check_notifications_type_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index('ix_notifications_is_read', 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index('ix_notifications_recipient', 'notifications', ['recipient_type', 'recipient_id'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_type'), 'notifications', ['recipient_type'], unique=False)
    
    op.create_table('operational_admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operational_admins'))
    )
    op.create_index(op.f('ix_operational_admins_email'), 'operational_admins', ['email'], unique=True)
    op.create_index(op.f('ix_operational_admins_id'), 'operational_admins', ['id'], unique=False)
    op.create_index(op.f('ix_operational_admins_is_active'), 'operational_admins', ['is_active'], unique=False)
    
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_type', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('used_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_tokens'))
    )
    op.create_index(op.f('ix_password_reset_tokens_expires_at'), 'password_reset_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_is_used'), 'password_reset_tokens', ['is_used'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_index('ix_password_reset_tokens_token_valid', 'password_reset_tokens', ['token', 'is_used', 'expires_at'], unique=False)
    op.create_index('ix_password_reset_tokens_user', 'password_reset_tokens', ['user_type', 'user_id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_user_type'), 'password_reset_tokens', ['user_type'], unique=False)
    
    op.create_table('rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=False),
    sa.Column('rate_type', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price >= 0', name=op.f('ck_rates_check_rates_price_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rates'))
    )
    op.create_index(op.f('ix_rates_id'), 'rates', ['id'], unique=False)
    op.create_index(op.f('ix_rates_is_active'), 'rates', ['is_active'], unique=False)
    op.create_index(op.f('ix_rates_rate_type'), 'rates', ['rate_type'], unique=False)
    op.create_index(op.f('ix_rates_vehicle_type'), 'rates', ['vehicle_type'], unique=False)
    op.create_index('ix_rates_vehicle_type_rate_type', 'rates', ['vehicle_type', 'rate_type'], unique=False)
    
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate', sa.String(length=20), nullable=False),
    sa.Column('owner_name', sa.String(length=100), nullable=False),
    sa.Column('owner_phone', sa.String(length=20), nullable=True),
    sa.Column('vehicle_type', sa.String(length=50), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('is_frequent', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicles'))
    )
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_index('ix_vehicles_is_frequent', 'vehicles', ['is_frequent'], unique=False)
    op.create_index('ix_vehicles_owner_name', 'vehicles', ['owner_name'], unique=False)
    op.create_index(op.f('ix_vehicles_plate'), 'vehicles', ['plate'], unique=True)
    op.create_index('ix_vehicles_vehicle_type', 'vehicles', ['vehicle_type'], unique=False)
    
    op.create_table('vouchers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voucher_number', sa.String(length=50), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_vouchers_check_vouchers_amount_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vouchers'))
    )
    op.create_index('ix_vouchers_entity', 'vouchers', ['entity'], unique=False)
    op.create_index(op.f('ix_vouchers_id'), 'vouchers', ['id'], unique=False)
    op.create_index(op.f('ix_vouchers_payment_date'), 'vouchers', ['payment_date'], unique=False)
    op.create_index(op.f('ix_vouchers_voucher_number'), 'vouchers', ['voucher_number'], unique=True)
    
    op.create_table('washers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('commission_percentage', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint('commission_percentage >= 0 AND commission_percentage <= 100', name=op.f('ck_washers_check_washers_commission_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_washers'))
    )
    op.create_index(op.f('ix_washers_email'), 'washers', ['email'], unique=True)
    op.create_index(op.f('ix_washers_id'), 'washers', ['id'], unique=False)
    op.create_index(op.f('ix_washers_is_active'), 'washers', ['is_active'], unique=False)
    
    op.create_table('monthly_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('monthly_fee', sa.Integer(), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("payment_status IN ('pending', 'paid', 'cancelled')", name=op.f('ck_monthly_subscriptions_check_monthly_subscriptions_payment_status_valid')),
    sa.CheckConstraint('end_date >= start_date', name=op.f('ck_monthly_subscriptions_check_monthly_subscriptions_dates_valid')),
    sa.CheckConstraint('monthly_fee >= 0', name=op.f('ck_monthly_subscriptions_check_monthly_subscriptions_fee_positive')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_monthly_subscriptions_vehicle_id_vehicles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monthly_subscriptions'))
    )
    op.create_index('ix_monthly_subscriptions_dates', 'monthly_subscriptions', ['start_date', 'end_date'], unique=False)
    op.create_index(op.f('ix_monthly_subscriptions_end_date'), 'monthly_subscriptions', ['end_date'], unique=False)
    op.create_index(op.f('ix_monthly_subscriptions_id'), 'monthly_subscriptions', ['id'], unique=False)
    op.create_index('ix_monthly_subscriptions_payment_status', 'monthly_subscriptions', ['payment_status'], unique=False)
    op.create_index(op.f('ix_monthly_subscriptions_start_date'), 'monthly_subscriptions', ['start_date'], unique=False)
    op.create_index(op.f('ix_monthly_subscriptions_vehicle_id'), 'monthly_subscriptions', ['vehicle_id'], unique=False)
    
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('initial_cash', sa.Integer(), nullable=True),
    sa.Column('final_cash', sa.Integer(), nullable=True),
    sa.Column('total_income', sa.Integer(), nullable=True),
    sa.Column('total_expenses', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('final_cash >= 0', name=op.f('ck_shifts_check_shifts_final_cash_positive')),
    sa.CheckConstraint('initial_cash >= 0', name=op.f('ck_shifts_check_shifts_initial_cash_positive')),
    sa.CheckConstraint('total_expenses >= 0', name=op.f('ck_shifts_check_shifts_total_expenses_positive')),
    sa.CheckConstraint('total_income >= 0', name=op.f('ck_shifts_check_shifts_total_income_positive')),
    sa.ForeignKeyConstraint(['admin_id'], ['operational_admins.id'], name=op.f('fk_shifts_admin_id_operational_admins'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shifts'))
    )
    op.create_index('ix_shifts_admin_date', 'shifts', ['admin_id', 'shift_date'], unique=False)
    op.create_index(op.f('ix_shifts_admin_id'), 'shifts', ['admin_id'], unique=False)
    op.create_index(op.f('ix_shifts_id'), 'shifts', ['id'], unique=False)
    op.create_index(op.f('ix_shifts_shift_date'), 'shifts', ['shift_date'], unique=False)
    
    op.create_table('parking_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('entry_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('exit_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('parking_rate_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('washing_service_id', sa.Integer(), nullable=True),
    sa.Column('helmet_count', sa.Integer(), nullable=True),
    sa.Column('helmet_charge', sa.Integer(), nullable=True),
    sa.Column('total_cost', sa.Integer(), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("payment_status IN ('pending', 'paid', 'cancelled')", name=op.f('ck_parking_records_check_parking_records_payment_status_valid')),
    sa.CheckConstraint('total_cost >= 0', name=op.f('ck_parking_records_check_parking_records_total_cost_positive')),
    sa.ForeignKeyConstraint(['admin_id'], ['operational_admins.id'], name=op.f('fk_parking_records_admin_id_operational_admins'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parking_rate_id'], ['rates.id'], name=op.f('fk_parking_records_parking_rate_id_rates'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name=op.f('fk_parking_records_shift_id_shifts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subscription_id'], ['monthly_subscriptions.id'], name=op.f('fk_parking_records_subscription_id_monthly_subscriptions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_parking_records_vehicle_id_vehicles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parking_records'))
    )
    op.create_index(op.f('ix_parking_records_admin_id'), 'parking_records', ['admin_id'], unique=False)
    op.create_index('ix_parking_records_entry_time', 'parking_records', ['entry_time'], unique=False)
    op.create_index('ix_parking_records_exit_time', 'parking_records', ['exit_time'], unique=False)
    op.create_index(op.f('ix_parking_records_id'), 'parking_records', ['id'], unique=False)
    op.create_index('ix_parking_records_payment_status', 'parking_records', ['payment_status'], unique=False)
    op.create_index(op.f('ix_parking_records_shift_id'), 'parking_records', ['shift_id'], unique=False)
    op.create_index(op.f('ix_parking_records_vehicle_id'), 'parking_records', ['vehicle_id'], unique=False)
    
    op.create_table('washing_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('parking_record_id', sa.Integer(), nullable=True),
    sa.Column('washer_id', sa.Integer(), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('service_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("payment_status IN ('pending', 'paid', 'cancelled')", name=op.f('ck_washing_services_check_washing_services_payment_status_valid')),
    sa.CheckConstraint('price >= 0', name=op.f('ck_washing_services_check_washing_services_price_positive')),
    sa.ForeignKeyConstraint(['admin_id'], ['operational_admins.id'], name=op.f('fk_washing_services_admin_id_operational_admins'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parking_record_id'], ['parking_records.id'], name=op.f('fk_washing_services_parking_record_id_parking_records'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name=op.f('fk_washing_services_shift_id_shifts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_washing_services_vehicle_id_vehicles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['washer_id'], ['washers.id'], name=op.f('fk_washing_services_washer_id_washers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_washing_services')),
    sa.UniqueConstraint('parking_record_id', name=op.f('uq_washing_services_parking_record_id'))
    )
    op.create_index(op.f('ix_washing_services_admin_id'), 'washing_services', ['admin_id'], unique=False)
    op.create_index(op.f('ix_washing_services_id'), 'washing_services', ['id'], unique=False)
    op.create_index('ix_washing_services_payment_status', 'washing_services', ['payment_status'], unique=False)
    op.create_index('ix_washing_services_service_date', 'washing_services', ['service_date'], unique=False)
    op.create_index(op.f('ix_washing_services_shift_id'), 'washing_services', ['shift_id'], unique=False)
    op.create_index(op.f('ix_washing_services_vehicle_id'), 'washing_services', ['vehicle_id'], unique=False)
    
    op.create_table('agreement_vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agreement_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], name=op.f('fk_agreement_vehicles_agreement_id_agreements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_agreement_vehicles_vehicle_id_vehicles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agreement_vehicles'))
    )
    op.create_index(op.f('ix_agreement_vehicles_agreement_id'), 'agreement_vehicles', ['agreement_id'], unique=False)
    op.create_index(op.f('ix_agreement_vehicles_id'), 'agreement_vehicles', ['id'], unique=False)
    op.create_index('ix_agreement_vehicles_unique', 'agreement_vehicles', ['agreement_id', 'vehicle_id'], unique=True)
    op.create_index(op.f('ix_agreement_vehicles_vehicle_id'), 'agreement_vehicles', ['vehicle_id'], unique=False)
    
    op.create_table('business_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('config_value', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('data_type', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("data_type IN ('string', 'integer', 'boolean', 'json')", name=op.f('ck_business_config_check_business_config_data_type_valid')),
    sa.ForeignKeyConstraint(['updated_by'], ['global_admins.id'], name=op.f('fk_business_config_updated_by_global_admins'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_config'))
    )
    op.create_index(op.f('ix_business_config_config_key'), 'business_config', ['config_key'], unique=True)
    op.create_index(op.f('ix_business_config_id'), 'business_config', ['id'], unique=False)
    
    op.create_table('employee_advances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('washer_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('number_of_installments', sa.Integer(), nullable=False),
    sa.Column('installment_amount', sa.Integer(), nullable=False),
    sa.Column('remaining_amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'paid', 'cancelled')", name=op.f('ck_employee_advances_check_advances_status_valid')),
    sa.CheckConstraint('installment_amount > 0', name=op.f('ck_employee_advances_check_advances_installment_amount_positive')),
    sa.CheckConstraint('number_of_installments > 0', name=op.f('ck_employee_advances_check_advances_installments_positive')),
    sa.CheckConstraint('total_amount > 0', name=op.f('ck_employee_advances_check_advances_total_amount_positive')),
    sa.ForeignKeyConstraint(['washer_id'], ['washers.id'], name=op.f('fk_employee_advances_washer_id_washers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_advances'))
    )
    op.create_index(op.f('ix_employee_advances_id'), 'employee_advances', ['id'], unique=False)
    op.create_index(op.f('ix_employee_advances_status'), 'employee_advances', ['status'], unique=False)
    op.create_index(op.f('ix_employee_advances_washer_id'), 'employee_advances', ['washer_id'], unique=False)
    
    op.create_table('bonuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('washer_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('bonus_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_bonuses_check_bonuses_amount_positive')),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name=op.f('fk_bonuses_shift_id_shifts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['washer_id'], ['washers.id'], name=op.f('fk_bonuses_washer_id_washers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bonuses'))
    )
    op.create_index('ix_bonuses_bonus_date', 'bonuses', ['bonus_date'], unique=False)
    op.create_index(op.f('ix_bonuses_id'), 'bonuses', ['id'], unique=False)
    op.create_index(op.f('ix_bonuses_shift_id'), 'bonuses', ['shift_id'], unique=False)
    op.create_index('ix_bonuses_washer_date', 'bonuses', ['washer_id', 'bonus_date'], unique=False)
    op.create_index(op.f('ix_bonuses_washer_id'), 'bonuses', ['washer_id'], unique=False)
    
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('expense_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_expenses_check_expenses_amount_positive')),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name=op.f('fk_expenses_shift_id_shifts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expenses'))
    )
    op.create_index(op.f('ix_expenses_expense_date'), 'expenses', ['expense_date'], unique=False)
    op.create_index('ix_expenses_expense_type', 'expenses', ['expense_type'], unique=False)
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.create_index(op.f('ix_expenses_shift_id'), 'expenses', ['shift_id'], unique=False)
    
    op.create_table('financial_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('report_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('generated_by', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('total_income', sa.Integer(), nullable=True),
    sa.Column('total_expenses', sa.Integer(), nullable=True),
    sa.Column('net_profit', sa.Integer(), nullable=True),
    sa.Column('parking_count', sa.Integer(), nullable=True),
    sa.Column('washing_count', sa.Integer(), nullable=True),
    sa.Column('subscription_count', sa.Integer(), nullable=True),
    sa.Column('report_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("report_type IN ('daily', 'weekly', 'monthly', 'yearly')", name=op.f('ck_financial_reports_check_financial_reports_type_valid')),
    sa.ForeignKeyConstraint(['generated_by'], ['global_admins.id'], name=op.f('fk_financial_reports_generated_by_global_admins'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name=op.f('fk_financial_reports_shift_id_shifts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_reports'))
    )
    op.create_index(op.f('ix_financial_reports_id'), 'financial_reports', ['id'], unique=False)
    op.create_index(op.f('ix_financial_reports_report_date'), 'financial_reports', ['report_date'], unique=False)
    op.create_index(op.f('ix_financial_reports_report_type'), 'financial_reports', ['report_type'], unique=False)
    op.create_index('ix_financial_reports_type_date', 'financial_reports', ['report_type', 'report_date'], unique=False)
    
    # Add circular FK
    op.create_foreign_key(op.f('fk_parking_records_washing_service_id_washing_services'), 'parking_records', 'washing_services', ['washing_service_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Revertir los cambios (rollback).
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_parking_records_washing_service_id_washing_services'), 'parking_records', type_='foreignkey')
    op.drop_index('ix_financial_reports_type_date', table_name='financial_reports')
    op.drop_index(op.f('ix_financial_reports_report_type'), table_name='financial_reports')
    op.drop_index(op.f('ix_financial_reports_report_date'), table_name='financial_reports')
    op.drop_index(op.f('ix_financial_reports_id'), table_name='financial_reports')
    op.drop_table('financial_reports')
    op.drop_index(op.f('ix_expenses_shift_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.drop_index('ix_expenses_expense_type', table_name='expenses')
    op.drop_index(op.f('ix_expenses_expense_date'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_bonuses_washer_id'), table_name='bonuses')
    op.drop_index('ix_bonuses_washer_date', table_name='bonuses')
    op.drop_index(op.f('ix_bonuses_shift_id'), table_name='bonuses')
    op.drop_index(op.f('ix_bonuses_id'), table_name='bonuses')
    op.drop_index('ix_bonuses_bonus_date', table_name='bonuses')
    op.drop_table('bonuses')
    op.drop_index(op.f('ix_employee_advances_washer_id'), table_name='employee_advances')
    op.drop_index(op.f('ix_employee_advances_status'), table_name='employee_advances')
    op.drop_index(op.f('ix_employee_advances_id'), table_name='employee_advances')
    op.drop_table('employee_advances')
    op.drop_index(op.f('ix_business_config_id'), table_name='business_config')
    op.drop_index(op.f('ix_business_config_config_key'), table_name='business_config')
    op.drop_table('business_config')
    op.drop_index(op.f('ix_agreement_vehicles_vehicle_id'), table_name='agreement_vehicles')
    op.drop_index('ix_agreement_vehicles_unique', table_name='agreement_vehicles')
    op.drop_index(op.f('ix_agreement_vehicles_id'), table_name='agreement_vehicles')
    op.drop_index(op.f('ix_agreement_vehicles_agreement_id'), table_name='agreement_vehicles')
    op.drop_table('agreement_vehicles')
    op.drop_index(op.f('ix_washing_services_vehicle_id'), table_name='washing_services')
    op.drop_index(op.f('ix_washing_services_shift_id'), table_name='washing_services')
    op.drop_index('ix_washing_services_service_date', table_name='washing_services')
    op.drop_index('ix_washing_services_payment_status', table_name='washing_services')
    op.drop_index(op.f('ix_washing_services_id'), table_name='washing_services')
    op.drop_index(op.f('ix_washing_services_admin_id'), table_name='washing_services')
    op.drop_table('washing_services')
    op.drop_index(op.f('ix_parking_records_vehicle_id'), table_name='parking_records')
    op.drop_index(op.f('ix_parking_records_shift_id'), table_name='parking_records')
    op.drop_index('ix_parking_records_payment_status', table_name='parking_records')
    op.drop_index(op.f('ix_parking_records_id'), table_name='parking_records')
    op.drop_index('ix_parking_records_exit_time', table_name='parking_records')
    op.drop_index('ix_parking_records_entry_time', table_name='parking_records')
    op.drop_index(op.f('ix_parking_records_admin_id'), table_name='parking_records')
    op.drop_table('parking_records')
    op.drop_index(op.f('ix_shifts_shift_date'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_id'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_admin_id'), table_name='shifts')
    op.drop_index('ix_shifts_admin_date', table_name='shifts')
    op.drop_table('shifts')
    op.drop_index(op.f('ix_monthly_subscriptions_vehicle_id'), table_name='monthly_subscriptions')
    op.drop_index(op.f('ix_monthly_subscriptions_start_date'), table_name='monthly_subscriptions')
    op.drop_index('ix_monthly_subscriptions_payment_status', table_name='monthly_subscriptions')
    op.drop_index(op.f('ix_monthly_subscriptions_id'), table_name='monthly_subscriptions')
    op.drop_index(op.f('ix_monthly_subscriptions_end_date'), table_name='monthly_subscriptions')
    op.drop_index('ix_monthly_subscriptions_dates', table_name='monthly_subscriptions')
    op.drop_table('monthly_subscriptions')
    op.drop_index(op.f('ix_washers_is_active'), table_name='washers')
    op.drop_index(op.f('ix_washers_id'), table_name='washers')
    op.drop_index(op.f('ix_washers_email'), table_name='washers')
    op.drop_table('washers')
    op.drop_index(op.f('ix_vouchers_voucher_number'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_payment_date'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_id'), table_name='vouchers')
    op.drop_index('ix_vouchers_entity', table_name='vouchers')
    op.drop_table('vouchers')
    op.drop_index('ix_vehicles_vehicle_type', table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_plate'), table_name='vehicles')
    op.drop_index('ix_vehicles_owner_name', table_name='vehicles')
    op.drop_index('ix_vehicles_is_frequent', table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index('ix_rates_vehicle_type_rate_type', table_name='rates')
    op.drop_index(op.f('ix_rates_vehicle_type'), table_name='rates')
    op.drop_index(op.f('ix_rates_rate_type'), table_name='rates')
    op.drop_index(op.f('ix_rates_is_active'), table_name='rates')
    op.drop_index(op.f('ix_rates_id'), table_name='rates')
    op.drop_table('rates')
    op.drop_index(op.f('ix_password_reset_tokens_user_type'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index('ix_password_reset_tokens_user', table_name='password_reset_tokens')
    op.drop_index('ix_password_reset_tokens_token_valid', table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_is_used'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_expires_at'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_operational_admins_is_active'), table_name='operational_admins')
    op.drop_index(op.f('ix_operational_admins_id'), table_name='operational_admins')
    op.drop_index(op.f('ix_operational_admins_email'), table_name='operational_admins')
    op.drop_table('operational_admins')
    op.drop_index(op.f('ix_notifications_recipient_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    op.drop_index('ix_notifications_recipient', table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index('ix_notifications_is_read', table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_global_admins_is_active'), table_name='global_admins')
    op.drop_index(op.f('ix_global_admins_id'), table_name='global_admins')
    op.drop_index(op.f('ix_global_admins_email'), table_name='global_admins')
    op.drop_table('global_admins')
    op.drop_index(op.f('ix_audit_logs_user_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_user', table_name='audit_logs')
    op.drop_index('ix_audit_logs_timestamp', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_agreements_is_active', table_name='agreements')
    op.drop_index(op.f('ix_agreements_id'), table_name='agreements')
    op.drop_index(op.f('ix_agreements_company_name'), table_name='agreements')
    op.drop_table('agreements')
    # ### end Alembic commands ###
